# Generated by Django 5.2.4 on 2025-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='chat_room_pictures/'),
        ),
    ]
